config/routes.rb
Rails.application.routes.draw do
  root "locations#index"

  resources :items
  resources :locations
  
  get "/locations/:id/new_item", to: "locations#new_item", as: "location_new_item"
  get "/locations/:id/new_inventory", to: "locations#new_inventory", as: "location_new_inventory"
  post "/locations/:id/items", to: "items#create", as: "location_items"

  get "/inventories/:id", to: "items#edit_inventory", as: "edit_inventory"
  patch "/inventories/:id/items", to: "items#inventory_items", as: "inventory_items"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :item, optional: true
  belongs_to :location, optional: true

  has_many :items, dependent: :nullify

  has_one_attached :picture
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  has_many :items, dependent: :nullify

  has_one_attached :picture
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit edit_inventory inventory_items update destroy ]

  def show
    @location = @item.location
    @items = @item.items
  end

  def new
    @item = Item.new
    @locations = Location.all
  end

  def edit
    @location = @item.location
    @locations = Location.all
  end

  def edit_inventory
    redirect_to item_path(@item) unless @item.container

    @location = @item.location

    if @location
      @items = @location.items
    else
      @items = Item.all
    end

    @selected_items_ids = @item.items.pluck(:id).to_a
  end

  def inventory_items
    redirect_to item_path(@item) unless @item.container

    selected_items = Item.where(id: params[:item][:item_ids])
    @item.items = selected_items

    redirect_to item_path(@item)
  end

  def create
    @item = Item.new(item_params)

    @item.picture.attach(params[:picture]) if params[:picture]

    if @item.save
      redirect_to item_url(@item), notice: "Item was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    was_inventory = @item.container

    if @item.update(item_params)
      if was_inventory && (@item.container == false)
        @item.items.update(item_id: nil)
        redirect_to item_url(@item), notice: "Item was successfully updated. Any contained items were removed."
      else
        redirect_to item_url(@item), notice: "Item was successfully updated."
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy

    redirect_to locations_url, notice: "Item was successfully deleted."
  end

  private
    def set_item
      @item = Item.includes(:location, :item).find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :notes, :item_id, :container, :location_id, :picture)
    end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy new_item new_inventory ]

  def index
    @locations = Location.all
    @unlocated_items = Item.all.where(location_id: nil)
  end

  def show
    @inventories = @location.items.where(container: true)
    @items = @location.items.where(container: false)
  end

  def new
    @location = Location.new
  end

  def new_item
    @item = Item.new
  end

  def new_inventory
    @item = Item.new
  end

  def edit
  end

  def create
    @location = Location.new(location_params)

    @location.picture.attach(params[:picture]) if params[:picture]

    if @location.save
      redirect_to location_url(@location), notice: "Location #{@location.id} was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @location.update(location_params)
      redirect_to location_url(@location), notice: "Location #{@location.id} was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @location.destroy

    redirect_to locations_url, notice: "Location #{@location.id} was successfully destroyed."
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <div>
    <% if item.errors.any? %>
      <div>
        <h2><%= pluralize(item.errors.count, "error") %> prevented this item from being saved:</h2>

        <ul>
          <% item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="flex justify-start mb-2">
      <%= form.label :container, "Inventory", class: "mr-4" %>
      <%= form.check_box :container %>
    </div>

    <div class="flex justify-start mb-2">
      <%= form.label :location_id, class: "mr-4" %>
      <%= form.select :location_id, @locations.map { |l| [ l.name, l.id ] }, { include_blank: true, selected: @location&.id } %>
    </div>

    <div class="mb-1">
      <%= form.label :name %>
      <%= form.text_field :name, required: true %>
    </div>

    <div class="mb-1">
      <%= form.label :description %>
      <%= form.text_area :description, required: true %>
    </div>

    <div class="mb-1">
      <%= form.label :notes %>
      <%= form.text_area :notes %>
    </div>

    <div class="mb-1">
      <%= form.file_field :picture, title: "Add a picture" %>
    </div>
  
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1 class="fs-8 mb-4">
  Editing item: <a class="text-link" href="<%= item_path(@item) %>">
                  <%= @item.name %>
                </a>
          <% if @location %>
            at <a class="text-link" href="<%= location_path(@location) %>">
                  <%= @location.name %>
                </a>
          <% end %>
</h1>

<%= render "form", item: @item %>

app/views/items/edit_inventory.html.erb
<%= render partial: "items/edit_inventory/heading" %>

<%= render partial: "items/edit_inventory/form" %>

app/views/items/edit_inventory/_form.html.erb
<%= form_with(model: @item, url: inventory_items_path(@item)) do |form| %>
  <h2 class="fs-5">Select the items in this inventory:</h2>
  <div class="mb-2">
    <%= collection_check_boxes(:item, :item_ids, @items, :id, :name, { selected: @selected_items_ids }) do |b| %>
      <div class="flex justify-start mb-1">
        <%= b.check_box class: "mr-2" %>
        <%= b.label %>
      </div>
    <% end %>
  </div>

  <%= form.submit %>
<% end %>

app/views/items/edit_inventory/_heading.html.erb
<h1 class="fs-8 mb-2">
  Editing inventory: <a class="text-link" href="<%= item_path(@item) %>">
                  <%= @item.name %>
                </a>
          <% if @location %>
            at <a class="text-link" href="<%= location_path(@location) %>">
                  <%= @location.name %>
                </a>
          <% end %>
</h1>

app/views/items/new.html.erb
<h1 class="fs-8 text-align-center border-bottom-4 border-style-groove">New item</h1>

<%= render "form", item: @item %>

app/views/items/show.html.erb
<p><%= notice %></p>

<div id="<%= dom_id @item %>">
  
  <%= render partial: "items/show/heading" %>

  <%= render partial: "items/show/item" %>

  <% if @item.container %>
    <%= render partial: "items/show/items" %>
  <% end %>

  <%= render partial: "items/show/picture" %>
</div>

app/views/items/show/_heading.html.erb
<div class="flex justify-between align-items-center mb-2">
  <h1 class="fs-8">
      <%= @item.name %>
      <% if @location %>
      at <a class="text-link" href="<%= location_path(@location) %>">
                        <%= @location.name %>
                      </a>
      <% end %>
  </h1>

  <div class="flex justify-around flex-1">
              <%= link_to "Edit this item", edit_item_path(@item), class: "text-link" %>

              <%= button_to "Destroy this item", @item,
                      method: :delete,
                      class: "danger-button",
                      form:
  { data: { turbo_confirm: "Are you sure you want to delete #{@item.name}?"} }
      %>
  </div>
</div>

app/views/items/show/_item.html.erb
<div class="mb-2">
  <p>
    <strong>Description: </strong><%= @item.description %>
  </p>

  <p>
    <strong>Notes: </strong><%= @item.notes %>
  </p>

  <% if @location %>
    <p>
      <strong>Location: </strong><%= @location.name %>
    </p>
  <% end %>
</div>

app/views/items/show/_items.html.erb
<h2 class="fs-6 mb-2">There are <%= @items.count %> items in this inventory:</h2>

<div class="flex flex-wrap mb-2">
  <% @items.each do |item| %>
    <a class="box-link
            inline-block text-align-center cursor-pointer flex flex-col justify-left flex-auto
            border-around-2 border-style-ridge"
        href="<%= item_path(item) %>">

                      <div class="pl-4 pr-4 pt-2 pb-2 flex flex-col justify-start">
                        <div>
                          <%= item.name %>
                        </div>
                      </div>

    </a>
  <% end %>

</div>

<%= link_to "Edit inventory", edit_inventory_path(@item), class: "text-link" %>

app/views/items/show/_picture.html.erb
<% picture = @item.picture %>

<% if picture&.representable? %>
  <div class="mt-4 flex justify-center">
    <div><%= image_tag picture.representation(resize_to_limit: [700, 500]) %></div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="font-gill-sans">
    <header class="bg-light-gray header-box-shadow h-12 p-4 mb-4 flex justify-between align-items-center">
      <div class="inline flex align-items-center">
        <span class="mr-2">
          <%= render partial: "layouts/heroicons/cube",
                locals: { css_class: "inline w-8 h-8" } %>
        </span>

        <span class="fs-5">Inventory</span>
      </div>

      <nav class="flex-1 sm-hidden">
        <ul class="flex justify-end">
          <li class="inline mr-4"><%= link_to "New location", new_location_path, class: "text-link" %></li>
          <li class="inline mr-4"><%= link_to "New item", new_item_path, class: "text-link" %></li>
          <li class="inline mr-4"><%= link_to "Locations", locations_path, class: "text-link" %></li>
        </ul>
      </nav>

      <div class="inline mr-2 sm-show" data-controller="hamburger">
        <button type="button" data-hamburger-target="showButton" title="Show navigation menu">
          <%= render partial: "layouts/heroicons/hamburger",
                      locals: { css_class: "inline w-8 h-8" } %>
        </button>

        <button class="display-none" type="button" data-hamburger-target="hideButton" title="Hide navigation menu">
          <%= render partial: "layouts/heroicons/x",
                      locals: { css_class: "inline w-8 h-8" } %>
        </button>

        <div class="position-fixed display-none top-12 right-4 bg-dark-white p-2 border-around-2 border-style-solid" data-hamburger-target="menu">
          <ul>
            <li><%= link_to "New location", new_location_path, class: "text-link" %></li>
            <li><%= link_to "New item", new_item_path, class: "text-link" %></li>
            <li><%= link_to "Locations", locations_path, class: "text-link" %></li>
          </ul>
        </div>
      </div>
    </header>

    <main class="ml-4 mr-4 mb-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/heroicons/_cube.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="<%= css_class %>">
  <path stroke-linecap="round" stroke-linejoin="round" d="m21 7.5-9-5.25L3 7.5m18 0-9 5.25m9-5.25v9l-9 5.25M3 7.5l9 5.25M3 7.5v9l9 5.25m0-9v9" />
</svg>

app/views/layouts/heroicons/_hamburger.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="<%= css_class %>">
  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
</svg>

app/views/layouts/heroicons/_x.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="<%= css_class %>">
  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
</svg>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <div>
    <% if location.errors.any? %>
      <div>
        <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

        <ul>
          <% location.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-1">
      <%= form.label :name %>
      <%= form.text_field :name, required: true %>
    </div>

    <div class="mb-1">
      <%= form.label :description %>
      <%= form.text_area :description, rows: 4 %>
    </div>

    <div class="mb-1">
      <%= form.file_field :picture, title: "Add a picture" %>
    </div>

    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1 class="fs-8 mb-2">Editing location <%= @location.id %></h1>

<%= render "form", location: @location %>

app/views/locations/index.html.erb
<p><%= notice %></p>

<div class="p-2">
  <h1 class="fs-8 mb-4
        ml-auto mr-auto width-half text-align-center
        border-bottom-4 border-style-groove">
    Locations
  </h1>

  <%= render partial: "locations/index/locations" %>

  <%= render partial: "locations/index/unlocated_items" %>
</div>

app/views/locations/index/_locations.html.erb
<div id="locations" class="flex flex-wrap">
  <% @locations.each do |location| %>
    <a id="<%= dom_id location %>"
        href="<%= location_path(location) %>"
        class="box-link
        inline-block text-align-center cursor-pointer
        border-around-2 border-style-ridge
        flex justify-around
        flex-1
        min-w-32 ml-2 mr-2 mb-4 p-4">
                <div class="flex flex-col">
                      <div class="fs-6 border-bottom-2 border-style-ridge">
                        <%= location.name %>
                      </div>

                      <div class="justify-around flex-1 p-4">
                        <span><%= location.description.truncate(200) %></span>
                      </div>

                      <div>
                        <%= location.items.count %> items
                      </div>
                </div>
    </a>
  <% end %>
</div>

app/views/locations/index/_unlocated_items.html.erb
<% if @unlocated_items.any? %>
  <h2>
    Unlocated items:
  </h2>

  <div class="flex justify-start">
    <% @unlocated_items.each do |uitem| %>
      <div>
        <a class="text-link" href="<%= edit_item_path(uitem) %>"><%= uitem.name %></a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/locations/items/_form.html.erb
<%= form_with(model: item, url: location_items_path(@location)) do |form| %>
  <div>
    <% if item.errors.any? %>
      <div>
        <h2><%= pluralize(item.errors.count, "error") %> prevented this item from being saved:</h2>

        <ul>
          <% item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-1">
      <%= form.label :name %>
      <%= form.text_field :name, required: true %>
    </div>

    <div class="mb-1">
      <%= form.label :description %>
      <%= form.text_area :description, required: true %>
    </div>

    <div class="mb-1">
      <%= form.label :notes %>
      <%= form.text_area :notes %>
    </div>

    <div class="mb-1">
      <%= form.file_field :picture, title: "Add a picture" %>
    </div>
  
    <%= form.submit %>

    <%= form.hidden_field :location_id, value: @location.id %>

    <%= form.hidden_field :container, value: is_container %>
  </div>
<% end %>

app/views/locations/new.html.erb
<h1 class="fs-8 text-align-center border-bottom-4 border-style-groove">New location</h1>

<%= render "form", location: @location %>

app/views/locations/new_inventory.html.erb
<h1 class="fs-8">New inventory (for <%= link_to @location.name, location_path(@location), class: "text-link" %>)</h1>

<%= render "locations/items/form", item: @item, is_container: true %>

app/views/locations/new_item.html.erb
<h1 class="fs-8">New item (for <%= link_to @location.name, location_path(@location), class: "text-link" %>)</h1>

<%= render "locations/items/form", item: @item, is_container: false %>

app/views/locations/show.html.erb
<p><%= notice %></p>

<div id="<%= dom_id @location %>">
  <%= render partial: "locations/show/heading" %>

  <%= render partial: "locations/show/location" %>

  <%= render partial: "locations/show/inventories" %>

  <%= render partial: "locations/show/items" %>

  <%= render partial: "locations/show/picture" %>
</div>

app/views/locations/show/_heading.html.erb
<div class="flex justify-between align-items-center mb-2">
  <h1 class="fs-8">
    <%= @location.name %>
  </h1>

  <div class="flex">
      <%= link_to "Edit location", edit_location_path(@location), class: "text-link mr-4" %>

      <%= button_to "Delete location", @location, method: :delete, class: "inline danger-button",
              form: { data: { turbo_confirm: "Are you sure you want to delete #{@location.name}?"} } %>
  </div>
</div>

app/views/locations/show/_inventories.html.erb
<div class="flex justify-between align-items-center">
  <h2 class="fs-6">Inventories</h2>

  <a class="text-link" href="<%= location_new_inventory_path %>">New inventory</a>
</div>

<div class="mb-2 flex flex-wrap">
  <% @inventories.each do |inventory| %>
    <a class="box-link
            inline-block text-align-center cursor-pointer flex flex-col justify-left flex-auto
            border-around-2 border-style-ridge"
        href="<%= item_path inventory %>">

              <div class="pl-4 pr-4 pt-2 pb-2 flex flex-col justify-between">
                <div>
                  <%= inventory.name %>
                </div>

                <div>
                  <%= inventory.items.count %> items
                </div>
              </div>

    </a>
  <% end %>
</div>

app/views/locations/show/_items.html.erb
<div class="flex justify-between align-items-center">
  <h2 class="fs-6">Items</h2>

  <a class="text-link" href="<%= location_new_item_path(@location) %>">New item</a>
</div>

<div class="flex flex-wrap">
  <% @items.each do |item| %>
    <a class="box-link
            inline-block text-align-center cursor-pointer flex flex-col justify-left flex-auto
            border-around-2 border-style-ridge"
        href="<%= item_path(item) %>">

                      <div class="pl-4 pr-4 pt-2 pb-2 flex flex-col justify-start">
                        <div>
                          <%= item.name %>
                        </div>
                      </div>

    </a>
  <% end %>
</div>

app/views/locations/show/_location.html.erb
<div class="mb-2">
    <%= @location.description %>
</div>

app/views/locations/show/_picture.html.erb
<% picture = @location.picture %>

<% if picture&.representable? %>
  <div class="mt-4 flex justify-center">
    <div><%= image_tag picture.representation(resize_to_limit: [500, 400]) %></div>
  </div>
<% end %>